In [22]:
#Q1
import numpy as np
a=np.array([1,2,3,4,5])
b=a.copy()
c=a.copy()
for i in range(len(a)):
    a[i]=a[i]+2
print(a)
for i in range(len(b)):
    b[i]=b[i]*3
print(b)
for i in range(len(c)):
    c[i]=c[i]/2
print(c)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0 1 1 2 2]


In [36]:
#Q2
arr=np.array([1,2,3,6,4,5])
c=np.flip(arr)
print(c)

x=np.array([1,2,3,4,5,1,2,1,1,1])
z=np.bincount(x)
mf=np.argmax(z)
print(f"the most frequent value of x is: {mf}")
indices=np.where(x==mf)[0]
print(f"and the indices are: {indices}")

y=np.array([1,1,1,2,3,4,2,4,3,3])
a=np.bincount(y)
mf2=np.argmax(a)
print(f"the most frequent value of y is: {mf2}")
index=np.where(y==mf2)[0]
print(f"and the indices are: {index}")

[5 4 6 3 2 1]
the most frequent value of x is: 1
and the indices are: [0 5 7 8 9]
the most frequent value of y is: 1
and the indices are: [0 1 2]


In [38]:
#Q3
arr=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(arr[0,1])
print(arr[2,0])

20
70


In [45]:
#Q4
aryan=np.linspace(10,100,25)
print(aryan)
print(aryan.ndim)
print(aryan.shape)
print(aryan.size)
print(aryan.dtype)
print(aryan.nbytes)

t_aryan=aryan.reshape(25,1)
print(t_aryan)
t_aryan2=aryan.T
print(t_aryan2)
#reshape and t attribute give different answers

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
1
(25,)
25
float64
200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [50]:
#Q5
ucs420_aryan=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
print(f"mean is: {np.mean(ucs420_aryan)}")
print(f"median is: {np.median(ucs420_aryan)}")
print(f"max element is: {np.max(ucs420_aryan)}")
print(f"min element is: {np.min(ucs420_aryan)}")
print(f"unique element are: {np.unique(ucs420_aryan)}")
reshaped_ucs420_aryan=ucs420_aryan.reshape(4,3)
print(reshaped_ucs420_aryan)
resized_ucs420_aryan=np.resize(reshaped_ucs420_aryan,(2,3))
print(resized_ucs420_aryan)

mean is: 43.333333333333336
median is: 37.5
max element is: 90
min element is: 10
unique element are: [10 15 20 30 35 40 50 60 70 80 90]
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
[[10 20 30]
 [40 50 60]]
